name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build docker image
      run: docker build . --file Dockerfile --tag simonjodet/api_weather:${{ github.sha }} --tag simonjodet/api_weather:develop
    - name: Publish docker image to docker hub
      run: |
        docker login -u simonjodet -p ${{ secrets. DOCKER_HUB_TOKEN }}
        docker push simonjodet/api_weather --all-tags
